[21/Mar/2018 19:50:41] "GET /admin HTTP/1.0" 301 0
[21/Mar/2018 19:50:41] "GET /admin/ HTTP/1.0" 302 0
[21/Mar/2018 19:50:42] "GET /admin/login/?next=/admin/ HTTP/1.0" 200 1652
[21/Mar/2018 19:50:42] "GET /static/admin/css/base.css HTTP/1.0" 200 16066
[21/Mar/2018 19:50:42] "GET /static/admin/css/login.css HTTP/1.0" 200 1203
[21/Mar/2018 19:50:42] "GET /static/admin/css/fonts.css HTTP/1.0" 200 423
[21/Mar/2018 19:50:42] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.0" 200 80304
[21/Mar/2018 19:50:43] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.0" 200 81348
[21/Mar/2018 19:52:33] "POST /admin/login/?next=/admin/ HTTP/1.0" 302 0
[21/Mar/2018 19:52:33] "GET /admin/ HTTP/1.0" 200 2739
[21/Mar/2018 19:52:33] "GET /static/admin/css/dashboard.css HTTP/1.0" 200 412
[21/Mar/2018 19:52:33] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.0" 200 82564
[21/Mar/2018 19:52:34] "GET /static/admin/img/icon-addlink.svg HTTP/1.0" 200 331
[21/Mar/2018 19:52:34] "GET /static/admin/img/icon-changelink.svg HTTP/1.0" 200 380
[21/Mar/2018 19:52:39] "GET /admin/auth/user/ HTTP/1.0" 200 6490
[21/Mar/2018 19:52:39] "GET /static/admin/css/changelists.css HTTP/1.0" 200 6170
[21/Mar/2018 19:52:39] "GET /static/admin/js/core.js HTTP/1.0" 200 7976
[21/Mar/2018 19:52:39] "GET /admin/jsi18n/ HTTP/1.0" 200 7758
[21/Mar/2018 19:52:39] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.0" 200 258648
[21/Mar/2018 19:52:39] "GET /static/admin/js/jquery.init.js HTTP/1.0" 200 363
[21/Mar/2018 19:52:39] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.0" 200 6591
[21/Mar/2018 19:52:39] "GET /static/admin/js/actions.js HTTP/1.0" 200 6501
[21/Mar/2018 19:52:39] "GET /static/admin/js/urlify.js HTTP/1.0" 200 8186
[21/Mar/2018 19:52:39] "GET /static/admin/js/prepopulate.js HTTP/1.0" 200 1538
[21/Mar/2018 19:52:39] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.0" 200 128820
[21/Mar/2018 19:52:40] "GET /static/admin/img/search.svg HTTP/1.0" 200 458
[21/Mar/2018 19:52:40] "GET /static/admin/img/icon-yes.svg HTTP/1.0" 200 436
[21/Mar/2018 19:52:41] "GET /static/admin/img/tooltag-add.svg HTTP/1.0" 200 331
[21/Mar/2018 19:52:41] "GET /static/admin/img/sorting-icons.svg HTTP/1.0" 200 1097
Not Found: /
[21/Mar/2018 19:54:46] "GET / HTTP/1.0" 404 2023
Invalid HTTP_HOST header: '106.14.177.99:8000'. You may need to add u'106.14.177.99' to ALLOWED_HOSTS.
[21/Mar/2018 19:55:26] "GET / HTTP/1.1" 400 61353
Invalid HTTP_HOST header: '106.14.177.99:8000'. You may need to add u'106.14.177.99' to ALLOWED_HOSTS.
[21/Mar/2018 19:55:27] "GET /favicon.ico HTTP/1.1" 400 61435
[21/Mar/2018 19:56:09] "GET /admin/auth/user/ HTTP/1.0" 200 6490
[21/Mar/2018 19:56:13] "GET /admin/password_change/ HTTP/1.0" 200 2518
[21/Mar/2018 19:56:13] "GET /static/admin/css/forms.css HTTP/1.0" 200 8173
[21/Mar/2018 19:56:13] "GET /static/admin/css/widgets.css HTTP/1.0" 200 10340
[21/Mar/2018 19:56:19] "GET /admin/ HTTP/1.0" 200 2739
[21/Mar/2018 19:56:26] "GET /admin/auth/user/add/ HTTP/1.0" 200 5488
[21/Mar/2018 19:56:26] "GET /admin/jsi18n/ HTTP/1.0" 200 7758
[21/Mar/2018 19:56:26] "GET /static/admin/js/prepopulate_init.js HTTP/1.0" 200 495
[21/Mar/2018 19:56:26] "GET /static/admin/js/change_form.js HTTP/1.0" 200 712
[21/Mar/2018 19:56:29] "GET /admin/auth/ HTTP/1.0" 200 2616
[21/Mar/2018 19:56:31] "GET /admin/ HTTP/1.0" 200 2739
Not Found: /
[21/Mar/2018 19:56:33] "GET / HTTP/1.0" 404 2023
[21/Mar/2018 19:56:48] "GET /admin/ HTTP/1.0" 200 2739
[21/Mar/2018 19:59:57] "GET /index/ HTTP/1.0" 200 12
Performing system checks...

System check identified no issues (0 silenced).
March 21, 2018 - 19:50:12
Django version 1.11.11, using settings 'hello_world.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[21/Mar/2018 20:04:16] "GET / HTTP/1.0" 200 12
Performing system checks...

System check identified no issues (0 silenced).
March 21, 2018 - 20:04:06
Django version 1.11.11, using settings 'hello_world.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x35aea28>
Performing system checks...

Traceback (most recent call last):
  File "/data/django_venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/data/django_venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/data/django_venv/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/data/django_venv/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/data/django_venv/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/data/django_venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/data/django_venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/data/django_venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/data/django_venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/django_venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/data/django_venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/django_venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/django_venv/hello_world/hello_world/urls.py", line 22, in <module>
    url(r'^blog/', blog),
NameError: name 'blog' is not defined
Unhandled exception in thread started by <function wrapper at 0x1862a28>
Performing system checks...

Traceback (most recent call last):
  File "/data/django_venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/data/django_venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/data/django_venv/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/data/django_venv/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/data/django_venv/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/data/django_venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/data/django_venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/data/django_venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/data/django_venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/django_venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/data/django_venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/django_venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/django_venv/hello_world/hello_world/urls.py", line 20, in <module>
    url(r'^$', index),
NameError: name 'index' is not defined
